In [1]:
import pandas as pd

In [95]:
data = pd.read_csv("assesment_dataset.csv", index_col=0, sep=r'\s+')
data

,mock_rep1,mock_rep2,mock_rep3,sars_cov_rep1,sars_cov_rep2,sars_cov_rep3
converted_alias,,,,,,
ENSG00000290825,0.03958,0.08353,0.08404,0.08911,0.08877,0.06094
ENSG00000278267,1.92300,3.04400,2.72200,2.16500,2.15600,3.70100
ENSG00000284332,0.00000,0.00000,0.00000,0.00000,0.00000,0.18240
ENSG00000237613,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
ENSG00000186092,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
...,...,...,...,...,...,...
ENSG00000212907,6446.00000,9613.00000,11580.00000,6564.00000,6939.00000,7220.00000
ENSG00000198886,15420.00000,15630.00000,13400.00000,14620.00000,16650.00000,15730.00000
ENSG00000198786,8609.00000,9019.00000,7286.00000,7628.00000,9205.00000,8384.00000
ENSG00000198695,12270.00000,13240.00000,10410.00000,10550.00000,12490.00000,11460.00000
ENSG00000198727,7928.00000,7369.00000,6012.00000,7487.00000,8709.00000,8027.00000

In [15]:
filtered_data = data[(data != 0).any(axis=1)]
filtered_data

,mock_rep1,mock_rep2,mock_rep3,sars_cov_rep1,sars_cov_rep2,sars_cov_rep3
converted_alias,,,,,,
ENSG00000290825,0.03958,0.08353,0.08404,0.08911,0.08877,0.06094
ENSG00000278267,1.92300,3.04400,2.72200,2.16500,2.15600,3.70100
ENSG00000284332,0.00000,0.00000,0.00000,0.00000,0.00000,0.18240
ENSG00000290825,0.12210,0.04294,0.05760,0.04580,0.13690,0.12530
ENSG00000273874,0.96150,2.02900,0.68060,1.08200,1.07800,1.11000
...,...,...,...,...,...,...
ENSG00000212907,6446.00000,9613.00000,11580.00000,6564.00000,6939.00000,7220.00000
ENSG00000198886,15420.00000,15630.00000,13400.00000,14620.00000,16650.00000,15730.00000
ENSG00000198786,8609.00000,9019.00000,7286.00000,7628.00000,9205.00000,8384.00000
ENSG00000198695,12270.00000,13240.00000,10410.00000,10550.00000,12490.00000,11460.00000
ENSG00000198727,7928.00000,7369.00000,6012.00000,7487.00000,8709.00000,8027.00000

In [16]:
filtered_data.to_csv("filtered.csv")

In [75]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind

In [76]:
data = pd.read_csv("filtered.csv", index_col=0)

In [77]:
# Diferansiyel Ä°fade Analizi
def differential_expression(data):
    # Mock ve SARS-CoV sÃ¼tunlarÄ±
    mock_cols = [col for col in data.columns if col.startswith('mock_')]
    sars_cols = [col for col in data.columns if col.startswith('sars_')]
    
    # t-test yaparak p-value hesaplama
    p_values = data.apply(lambda row: ttest_ind(row[mock_cols], row[sars_cols])[1], axis=1)
    
    results = pd.DataFrame({
        'p_value': p_values,
        'significantly_changed': p_values < 0.05
    })
    
    return results

In [79]:
de_results = differential_expression(data)

In [81]:
significant_genes = de_results[de_results['significantly_changed']]
significant_genes

                  p_value  significantly_changed
converted_alias
ENSG00000284662  0.009101                   True
ENSG00000291156  0.013085                   True
ENSG00000248333  0.036266                   True
ENSG00000169598  0.009468                   True
ENSG00000236423  0.036745                   True
...                   ...                    ...
ENSG00000183837  0.006490                   True
ENSG00000102030  0.025413                   True
ENSG00000207165  0.033273                   True
ENSG00000071859  0.006995                   True
ENSG00000182712  0.024904                   True

[2071 rows x 2 columns]

In [86]:
significant_genes.to_csv("significant_genes.csv")

In [94]:
converted_alias_df = significant_genes.index.to_frame(name='converted_alias')
converted_alias_df.to_csv("enrichment.csv", index=False)